services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: code-analysis-backend
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: code-analysis-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: unless-stopped
