import type { StaticAnalysisRule } from "../../types/index.js";

export const cRules: StaticAnalysisRule[] = [
  {
    id: "c-gets",
    severity: "CRITICAL",
    type: "VULNERABILITY",
    language: "c",
    description: "gets() call",
    matcher: "query",
    query: '(call_expression function: (identifier) @f (#eq? @f "gets"))',
  },
  {
    id: "c-sprintf-overflow",
    severity: "CRITICAL",
    type: "BUG",
    language: "c",
    description: "sprintf call without length limit",
    matcher: "query",
    query: '(call_expression function: (identifier) @f (#eq? @f "sprintf"))',
  },
  {
    id: "c-null-check-after-deref",
    severity: "MAJOR",
    type: "BUG",
    language: "c",
    description: "pointer is dereferenced before null check",
    matcher: "ast-walk",
  },
  {
    id: "c-div-zero",
    severity: "MAJOR",
    type: "BUG",
    language: "c",
    description: "division by constant zero",
    matcher: "ast-walk",
  },
  {
    id: "c-hardcoded-secret",
    severity: "CRITICAL",
    type: "VULNERABILITY",
    language: "c",
    description: "hardcoded credential-like string",
    matcher: "ast-walk",
  },
  {
    id: "c-resource-leak",
    severity: "MAJOR",
    type: "BUG",
    language: "c",
    description: "malloc allocation without matching free",
    matcher: "ast-walk",
  },
  {
    id: "c-long-func",
    severity: "MINOR",
    type: "CODE_SMELL",
    language: "c",
    description: "function longer than 100 lines",
    matcher: "ast-walk",
  },
  {
    id: "c-too-many-params",
    severity: "MINOR",
    type: "CODE_SMELL",
    language: "c",
    description: "function with more than 6 parameters",
    matcher: "ast-walk",
  },
];
