import type { StaticAnalysisRule } from "../../types/index.js";

export const pythonRules: StaticAnalysisRule[] = [
  {
    id: "py-eval",
    severity: "CRITICAL",
    type: "VULNERABILITY",
    language: "python",
    description: "eval() or exec() call",
    matcher: "query",
    query: '(call function: (identifier) @f (#match? @f "^(eval|exec)$"))',
  },
  {
    id: "py-shell-true",
    severity: "CRITICAL",
    type: "VULNERABILITY",
    language: "python",
    description: "subprocess call with shell=True",
    matcher: "ast-walk",
  },
  {
    id: "py-bare-except",
    severity: "MAJOR",
    type: "BUG",
    language: "python",
    description: "bare except or broad except Exception",
    matcher: "ast-walk",
  },
  {
    id: "py-hardcoded-secret",
    severity: "CRITICAL",
    type: "VULNERABILITY",
    language: "python",
    description: "hardcoded credential-like assignment",
    matcher: "ast-walk",
  },
  {
    id: "py-open-no-close",
    severity: "MAJOR",
    type: "BUG",
    language: "python",
    description: "open() call outside with statement",
    matcher: "ast-walk",
  },
  {
    id: "py-assert-on-tuple",
    severity: "MAJOR",
    type: "BUG",
    language: "python",
    description: "assert on tuple expression",
    matcher: "query",
    query: "(assert_statement (tuple) @tuple)",
  },
  {
    id: "py-long-func",
    severity: "MINOR",
    type: "CODE_SMELL",
    language: "python",
    description: "function longer than 100 lines",
    matcher: "ast-walk",
  },
  {
    id: "py-too-many-params",
    severity: "MINOR",
    type: "CODE_SMELL",
    language: "python",
    description: "function with more than 6 parameters",
    matcher: "ast-walk",
  },
];
